[keyboard]
name = "rmk-sweep"
product_name = "rmk-sweep"
vendor_id = 0x4c4b
product_id = 0x4643
manufacturer = "RMK"
chip = "nrf52840"

[layout]
# WARNING: Currently row2col/col2row is set in RMK's feature gate, row2col config here is valid ONLY when you're using cloud compilation.
# Checkout doc here: https://rmk.rs/docs/user_guide/faq.html#my-matrix-is-row2col-the-matrix-doesn-t-work
# row2col = true
rows = 8
cols = 5
layers = 4
matrix_map = """
    (0,0) (0,1) (0,2) (0,3) (0,4)  (4,4) (4,3) (4,2) (4,1) (4,0)
    (1,0) (1,1) (1,2) (1,3) (1,4)  (5,4) (5,3) (5,2) (5,1) (5,0)
    (2,0) (2,1) (2,2) (2,3) (2,4)  (6,4) (6,3) (6,2) (6,1) (6,0)
                      (3,0) (3,1)  (7,1) (7,0)
"""

[aliases]
EXLM = "WM(Kc1, LShift)"
AT = "WM(Kc2, LShift)"
HASH = "WM(Kc3, LShift)"
DLR = "WM(Kc4, LShift)"
PERC = "WM(Kc5, LShift)"
CIRC = "WM(Kc6, LShift)"
AMPR = "WM(Kc7, LShift)"
ASTR = "WM(Kc8, LShift)"
LPRN = "WM(Kc9, LShift)"
RPRN = "WM(Kc0, LShift)"
UNDS = "WM(Minus, LShift)"
PLUS = "WM(Equal, LShift)"
LCBR = "WM(LeftBracket, LShift)"
RCBR = "WM(RightBracket, LShift)"
COLN = "WM(Semicolon, LShift)"
DQUO = "WM(Quote, LShift)"
PIPE = "WM(Backslash, LShift)"
TILD = "WM(Grave, LShift)"

BT0 = "User0"
BT1 = "User1"
BT2 = "User2"
BT_NEXT = "User3"
BT_PREV = "User4"
BT_CLR = "User5"
USB_BLE = "User6"

MUTE = "AudioMute"
VOLD = "AudioVolDown"
VOLU = "AudioVolUp"
MPLY = "MediaPlayPause"
MNXT = "MediaNextTrack"

SFT_A = "MT(A, LShift)"
CTL_Z = "MT(Z, LCtrl)"
SFT_QUO = "MT(Quote, RShift)"
GUI_COM = "MT(Comma, RGui)"
ALT_DOT = "MT(Dot, RAlt)"
CTL_SLS = "MT(Slash, RCtrl)"
SYM_TAB = "LT(1, Tab)"
NUM_BSP = "LT(2, Backspace)"

[[layer]]
name = "base"
keys = """
Q      W E R T Y U I        O        P
@SFT_A S D F G H J K        L        @SFT_QUO
@CTL_Z X C V B N M @GUI_COM @ALT_DOT @CTL_SLS
@SYM_TAB Enter Space @NUM_BSP
"""

[[layer]]
name = "upper"
keys = """
No    LeftBracket @LCBR @RCBR  No    @CIRC @LPRN @RPRN RightBracket @TILD
@EXLM @AT         @HASH @DLR   @PERC @AMPR Minus Equal Backslash    Grave
LCtrl LAlt        LGui  LShift No    @ASTR @UNDS @PLUS @PIPE        Slash
_ Escape _ MO(3)
"""

[[layer]]
name = "lower"
keys = """
Insert   Kc1 Kc2 Kc3 Minus Home PageDown PageUp End   @COLN
Delete   Kc4 Kc5 Kc6 Dot   Left Down     Up     Right Semicolon
CapsLock Kc7 Kc8 Kc9 Kc0   No   RShift   RGui   RAlt  RCtrl
MO(3) Escape _ _
"""

[[layer]]
name = "adjust"
keys = """
No F1 F2  F3  F4  @BT0  @BT1   @BT2  @BT_CLR @USB_BLE
No F5 F6  F7  F8  @MUTE @VOLD  @VOLU @MPLY   @MNXT
No F9 F10 F11 F12 No    RShift RGui  RAlt    RCtrl
_ _ _ _
"""

[behavior]
tap_hold = { enable_hrm = true, permissive_hold = true, unilateral_tap = true, hold_on_other_press = true }

[ble]
enabled = true

[split]
connection = "ble"

[split.central]
rows = 4
cols = 5
row_offset = 0
col_offset = 0
[split.central.matrix]
matrix_type = "direct_pin"
direct_pin_low_active = true
direct_pins = [
    ["P0_09", "P0_02", "P0_29", "P0_31", "P0_30"],
    ["P1_13", "P0_03", "P0_28", "P1_11", "P0_06"],
    ["P0_15", "P0_17", "P0_20", "P0_13", "P0_24"],
    ["P0_10", "P1_06", "_", "_", "_" ]
]

[[split.peripheral]]
rows = 4
cols = 5
row_offset = 4
col_offset = 0

[split.peripheral.matrix]
matrix_type = "direct_pin"
direct_pin_low_active = true
direct_pins = [
    ["P0_09", "P0_02", "P0_29", "P0_31", "P0_30"],
    ["P1_13", "P0_03", "P0_28", "P1_11", "P0_06"],
    ["P0_15", "P0_17", "P0_20", "P0_13", "P0_24"],
    ["P0_10", "P1_06", "_", "_", "_" ]
]
